package com.scsabot.discordbot.story.complete;

import com.scsabot.discordbot.dto.StoryStarter;
import com.scsabot.discordbot.service.RoleService;
import com.scsabot.discordbot.timer.TimerCommand;
import lombok.RequiredArgsConstructor;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.springframework.stereotype.Component;

import java.awt.*;
import java.util.Collections;

/**
 * /story complete - Story completion practice.
 * The bot shows the start of a story and the speaker finishes it.
 * <p>
 * - "🔄 Regenerate" edits the current message with a new story.
 * - "🗣️ Next Speaker" posts a new message with its own story.
 * - "⏱️ Start 3 min" starts a countdown timer as a separate message.
 */
@Component
@RequiredArgsConstructor
public class StoryCompleteCommand {

    public static final String REGENERATE_BUTTON_ID = "story:complete:regenerate";
    public static final String NEXT_SPEAKER_BUTTON_ID = "story:complete:nextspeaker";
    public static final String TIMER_BUTTON_ID = "story:complete:timer";

    private static final int TIMER_MINUTES = 2;
    private static final String NO_STORIES_MESSAGE =
            "❌ No stories are loaded yet — check data/story.";
    private static final String ROLE_KEY = "storyteller";

    private final StoryStarterLoader storyLoader;
    private final RoleService roleService;
    private final TimerCommand timerCommand;


    /**
     * Handles /story complete. Called from SlashCommandListener
     * for both /story complete and /practice.
     */
    public void handleCompleteCommand(SlashCommandInteractionEvent event) {

        StoryStarter story = storyLoader.randomStory();

        if (story == null) {
            event.reply(NO_STORIES_MESSAGE).setEphemeral(true).queue();
            return;
        }

        event.reply("Generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(buildEmbed(story).build())
                .addActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "🔄 Regenerate" - same speaker, edit the existing message in place.
     */
    public void handleRegenerate(ButtonInteractionEvent event) {

        StoryStarter story = storyLoader.randomStory();

        if (story == null) {
            event.reply(NO_STORIES_MESSAGE).setEphemeral(true).queue();
            return;
        }

        event.editMessage("Regenerated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .setEmbeds(buildEmbed(story).build())
                .setActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "🗣️ Next Speaker" - post a new message with its own story,
     * leaving the previous message untouched.
     */
    public void handleNextSpeaker(ButtonInteractionEvent event) {

        StoryStarter story = storyLoader.randomStory();

        if (story == null) {
            event.reply(NO_STORIES_MESSAGE).setEphemeral(true).queue();
            return;
        }

        event.reply("Generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(buildEmbed(story).build())
                .addActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "⏱️ Start 3 min" - starts a timer as a separate message,
     * leaving the story prompt untouched.
     */
    public void handleTimer(ButtonInteractionEvent event) {

        timerCommand.startFromButton(event, TIMER_MINUTES, "Story time's up!");

        // Optional: remove if starting a timer shouldn't count toward the role.
        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    private Button[] actionRow() {
        return new Button[]{
                Button.primary(REGENERATE_BUTTON_ID, "🔄 Regenerate"),
                Button.secondary(NEXT_SPEAKER_BUTTON_ID, "🗣️ Next Speaker"),
                Button.success(TIMER_BUTTON_ID, "⏱️ Start " + TIMER_MINUTES + " min")
        };
    }

    public EmbedBuilder buildEmbed(StoryStarter story) {
        EmbedBuilder embed = new EmbedBuilder();

        embed.setAuthor("✍️ Story Completion");
        embed.setTitle("📖 " + story.title());
        embed.setColor(new Color(0x5865F2));

        embed.setDescription(
                "**Finish this story in your own words!**\n\n"
                        + "> " + story.opening() + " **…**\n\n"
                        + "🎤 *Start from where the story stops. Any ending is a good ending.*"
        );

        embed.setFooter("Tip: Take your time. There is no wrong answer.");

        return embed;
    }
}