name: scsa-bot

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scsa-bot
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
