package com.scsabot.discordbot.tabletopics;


import com.scsabot.discordbot.dto.TableTopicQuestion;
import com.scsabot.discordbot.dto.TableTopicSession;
import com.scsabot.discordbot.service.RoleService;
import lombok.RequiredArgsConstructor;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.springframework.stereotype.Component;

import java.util.Collections;

@Component
@RequiredArgsConstructor
public class TableTopicCommand {

    private static final String ROLE_KEY = "table-topic";

    private final TableTopicService topicService;
    private final TableTopicSessionManager sessionManager;
    private final RoleService roleService;


    /**
     * Builds the Discord card shown to the user.
     */
    public EmbedBuilder buildEmbed(TableTopicSession session) {

        TableTopicQuestion question = session.getQuestion();

        EmbedBuilder embed = new EmbedBuilder();

        embed.setTitle("🗣️ Table Topic");

        StringBuilder description = new StringBuilder();

        description.append("**")
                .append(question.question())
                .append("**");

        if (session.getPracticeWord() != null) {
            description.append("\n\n🎲 **Random Word:** `")
                    .append(session.getPracticeWord())
                    .append("`");

            embed.setFooter(
                    "Tip: Try to link the word to your Table Topic answer."
            );
        }

        embed.setDescription(description.toString());

        return embed;
    }

    /**
     * Handles /topic. Called from SlashCommandListener for both
     * /topic and /practice.
     */
    public void handleTopicCommand(
            SlashCommandInteractionEvent event
    ) {

        String category = event.getOption("category") != null
                ? event.getOption("category").getAsString()
                : null;

        String difficulty = event.getOption("difficulty") != null
                ? event.getOption("difficulty").getAsString()
                : null;

        TableTopicQuestion question =
                topicService.randomQuestion(
                        category,
                        difficulty,
                        null
                );

        if (question == null) {
            event.reply(
                    "❌ I couldn't find a topic matching those filters."
            ).setEphemeral(true).queue();
            return;
        }

        TableTopicSession session =
                new TableTopicSession(
                        category,
                        difficulty,
                        question
                );

        String sessionId =
                sessionManager.createSession(session);

        event.reply("Generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(buildEmbed(session).build())
                .addActionRow(
                        Button.primary(
                                "tabletopic:next:" + sessionId,
                                "➡️ Next Prompt"
                        ),
                        Button.secondary(
                                "tabletopic:word:" + sessionId,
                                "🎲 Word"
                        )
                )
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }
}