package com.scsabot.discordbot.tabletopics;

import com.scsabot.discordbot.dto.TableTopicQuestion;
import com.scsabot.discordbot.dto.TableTopicSession;
import com.scsabot.discordbot.service.RoleService;
import com.scsabot.discordbot.timer.TimerCommand;
import lombok.RequiredArgsConstructor;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.springframework.stereotype.Component;

import java.util.Collections;
import java.util.List;

@Component
@RequiredArgsConstructor
public class TableTopicButtonListener extends ListenerAdapter {

    private static final String ROLE_KEY = "table-topic";
    private static final int TIMER_MINUTES = 2;

    private final TableTopicService topicService;
    private final TableTopicSessionManager sessionManager;
    private final TableTopicCommand topicCommand;
    private final RoleService roleService;
    private final TimerCommand timerCommand;

    /**
     * Single source of truth for the Table Topic buttons.
     * Also use this in TableTopicCommand when posting the first prompt.
     */
    public static List<Button> buttons(String sessionId) {
        return List.of(
                Button.primary("tabletopic:next:" + sessionId, "➡️ Next Prompt"),
                Button.secondary("tabletopic:word:" + sessionId, "🎲 Word"),
                Button.success("tabletopic:timer:" + sessionId, "⏱️ Start " + TIMER_MINUTES + " min")
        );
    }

    @Override
    public void onButtonInteraction(
            ButtonInteractionEvent event
    ) {

        String componentId = event.getComponentId();

        if (!componentId.startsWith("tabletopic:")) {
            return;
        }

        String[] parts = componentId.split(":");

        if (parts.length != 3) {
            return;
        }

        String action = parts[1];
        String sessionId = parts[2];

        TableTopicSession session =
                sessionManager.getSession(sessionId);

        if (session == null) {

            event.reply(
                            "This Table Topic session has expired."
                    )
                    .setEphemeral(true)
                    .queue();

            return;
        }

        switch (action) {

            case "next" -> handleNext(event, session, sessionId);

            case "word" -> handleWord(event, session);

            case "timer" -> handleTimer(event);

            default -> {
                // Ignore unknown TableTopic buttons.
            }
        }
    }

    private void handleNext(
            ButtonInteractionEvent event,
            TableTopicSession session,
            String sessionId
    ) {

        TableTopicQuestion nextQuestion =
                topicService.randomQuestion(
                        session.getCategory(),
                        session.getDifficulty(),
                        session.getQuestion()
                );

        if (nextQuestion == null) {

            event.reply(
                            "❌ No other questions match the current filters."
                    )
                    .setEphemeral(true)
                    .queue();

            return;
        }

        session.setQuestion(nextQuestion);

        event.reply("Next prompt generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(topicCommand.buildEmbed(session).build())
                .addActionRow(buttons(sessionId))
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    private void handleWord(
            ButtonInteractionEvent event,
            TableTopicSession session
    ) {

        String word = topicService.randomWord();

        if (word == null) {

            event.reply(
                            "❌ No practice words are available."
                    )
                    .setEphemeral(true)
                    .queue();

            return;
        }

        session.setPracticeWord(word);

        event.editMessage("🎲 Word added by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .setEmbeds(topicCommand.buildEmbed(session).build())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    private void handleTimer(ButtonInteractionEvent event) {

        timerCommand.startFromButton(event, TIMER_MINUTES, "Table Topic time's up!");

        // Optional: remove if starting a timer shouldn't count toward the role.
        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }
}