spring:
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    root: INFO
    com.scsabot.discordbot: INFO

discord:
  bot-token: ${DISCORD_BOT_TOKEN:}
  guild-id: ${DISCORD_GUILD_ID:}

server:
  shutdown: graceful

pexels:
  api:
    key: ${PEXELS_API_KEY:}