spring:
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    root: INFO
    com.scsabot.discordbot: INFO

discord:
  bot-token: ${DISCORD_BOT_TOKEN:}
  guild-id: ${DISCORD_GUILD_ID:}
  stage-channel-id: "1546486694973546597"
  event-chat-channel-id: "1556933948402307092"

server:
  shutdown: graceful

pexels:
  api:
    key: ${PEXELS_API_KEY:}

unsplash:
  access:
    key: ${UNSPLASH_ACCESS_KEY:}

bot:
  roles:
    practice: "1555500219217481768"
    storyteller: "1555500402894700606"
    table-topic: "1555500291741319208"
    image-prompt: "1555500344791015504"