spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/discord_bot}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.scsabot.discordbot: INFO
    org.hibernate.SQL: WARN

discord:
  bot-token: ${DISCORD_BOT_TOKEN:}
  guild-id: ${DISCORD_GUILD_ID:}

server:
  shutdown: graceful
