package com.scsabot.discordbot.story;


import com.scsabot.discordbot.service.RoleService;
import com.scsabot.discordbot.tabletopics.TableTopicDataLoader;
import com.scsabot.discordbot.timer.TimerCommand;
import lombok.RequiredArgsConstructor;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.interaction.component.ButtonInteractionEvent;
import net.dv8tion.jda.api.interactions.components.buttons.Button;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * /story words - Story speaking practice.
 * Pulls 3 random words from the words loaded by {@link TableTopicDataLoader}
 * (data/words/*.json) and challenges the user to speak a short, connected
 * story that uses all three.
 * <p>
 * Three buttons:
 * - "🔄 Regenerate" edits the current message with a new set of words,
 * for the same speaker who wants different words.
 * - "🗣️ New Speaker" posts a brand new message with its own words,
 * leaving the previous speaker's message untouched.
 * - "⏱️ Start 3 min" starts a countdown timer as a separate message.
 */
@Component
@RequiredArgsConstructor
public class StoryWordsCommand {

    public static final String REGENERATE_BUTTON_ID = "story:words:regenerate";
    public static final String NEW_SPEAKER_BUTTON_ID = "story:words:newspeaker";
    public static final String TIMER_BUTTON_ID = "story:words:timer";

    private static final String ROLE_KEY = "storyteller";
    private static final int WORD_COUNT = 3;
    private static final int TIMER_MINUTES = 2;

    private final TableTopicDataLoader dataLoader;
    private final RoleService roleService;
    private final TimerCommand timerCommand;


    /**
     * Handles /story words. Called from SlashCommandListener
     * for both /story words and /practice.
     */
    public void handleStoryCommand(SlashCommandInteractionEvent event) {

        List<String> words = pickRandomWords();

        if (words.isEmpty()) {
            event.reply(
                    "❌ No practice words are loaded yet — check data/words."
            ).setEphemeral(true).queue();
            return;
        }

        event.reply("Generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(buildEmbed(words).build())
                .addActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "🔄 Regenerate" - same speaker, edit the existing message in place.
     */
    public void handleRegenerate(ButtonInteractionEvent event) {

        List<String> words = pickRandomWords();

        if (words.isEmpty()) {
            event.reply(
                    "❌ No practice words are loaded yet — check data/words."
            ).setEphemeral(true).queue();
            return;
        }

        event.editMessage("🔄 Regenerated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .setEmbeds(buildEmbed(words).build())
                .setActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "🗣️ New Speaker" - post a brand new message with its own words,
     * leaving the previous message (and its words) untouched.
     */
    public void handleNewSpeaker(ButtonInteractionEvent event) {

        List<String> words = pickRandomWords();

        if (words.isEmpty()) {
            event.reply(
                    "❌ No practice words are loaded yet — check data/words."
            ).setEphemeral(true).queue();
            return;
        }

        event.reply("Generated by " + event.getUser().getAsMention())
                .setAllowedMentions(Collections.emptyList())
                .addEmbeds(buildEmbed(words).build())
                .addActionRow(actionRow())
                .queue();

        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    /**
     * "⏱️ Start 3 min" - starts a timer as a separate message,
     * leaving the words prompt untouched.
     */
    public void handleTimer(ButtonInteractionEvent event) {

        timerCommand.startFromButton(event, TIMER_MINUTES, "Story time's up!");

        // Optional: remove if starting a timer shouldn't count toward the role.
        roleService.grantRoles(event.getMember(), ROLE_KEY);
    }

    private Button[] actionRow() {
        return new Button[]{
                Button.primary(REGENERATE_BUTTON_ID, "🔄 Regenerate"),
                Button.secondary(NEW_SPEAKER_BUTTON_ID, "🗣️ New Speaker"),
                Button.success(TIMER_BUTTON_ID, "⏱️ Start " + TIMER_MINUTES + " min")
        };
    }

    /**
     * Builds the Discord card shown to the user.
     */
    public EmbedBuilder buildEmbed(List<String> words) {
        EmbedBuilder embed = new EmbedBuilder();

        embed.setTitle("📖 Story Speaking Practice");

        StringBuilder description = new StringBuilder();
        description.append("Speak a short, connected story that naturally uses **all three** words below:\n\n");

        for (String word : words) {
            description.append("🔹 `").append(word).append("`\n");
        }

        embed.setDescription(description.toString());
        embed.setFooter("Tip: Decide the order and connect them with cause and effect, not just a list.");

        return embed;
    }

    private List<String> pickRandomWords() {
        List<String> pool = dataLoader.getWords();

        if (pool.isEmpty()) {
            return Collections.emptyList();
        }

        List<String> shuffled = new ArrayList<>(pool);
        Collections.shuffle(shuffled, ThreadLocalRandom.current());

        int count = Math.min(WORD_COUNT, shuffled.size());
        return shuffled.subList(0, count);
    }
}